# Generated by Django 2.1.2 on 2018-12-16 14:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadjaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_kreiranja', models.DateField(default=datetime.datetime(2018, 12, 16, 14, 19, 21, 33486, tzinfo=utc))),
                ('naziv', models.CharField(max_length=150)),
                ('datum_odrzavanja', models.DateField()),
                ('opis', models.TextField(max_length=350)),
                ('potrebno_igraca', models.PositiveIntegerField()),
                ('novcana_nagrada', models.CharField(choices=[('Ima novcane nagrade', 'Ima novcane nagrade'), ('Nema novcane nagrade', 'Nema novcane nagrade')], default='Nema novcane nagrade', max_length=100)),
                ('novac_za_prijavu', models.PositiveIntegerField(default=0)),
                ('grad', models.CharField(choices=[('Nije naveden grad', 'Nije naveden grad'), ('Beograd', 'Beograd'), ('Cacak', 'Cacak'), ('Uzice', 'Uzice'), ('Ivanjica', 'Ivanjica'), ('Novi sad', 'Novi sad'), ('Nis', 'Nis'), ('Pozega', 'Pozega'), ('Lucani', 'Lucani')], default='Nije naveden grad', max_length=254)),
                ('odrzano', models.BooleanField(default=False)),
                ('organizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
