# Generated by Django 2.1.2 on 2018-12-16 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogadjaji', '0002_auto_20181216_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_prijave', models.DateField(default=django.utils.timezone.now)),
                ('primljen', models.CharField(choices=[('Primljen', 'Primljen'), ('Odbijen', 'Odbijen'), ('Ceka se odgovor', 'Ceka se odgovor')], default='Ceka se odgovor', max_length=100)),
                ('prijava_za_dogadjaj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dogadjaji.Dogadjaj')),
                ('prijavu_poslao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
