# Generated by Django 2.1.2 on 2018-12-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0003_prijava'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogadjaj',
            name='sport',
            field=models.CharField(choices=[('Nije naveden omiljeni sport', 'Nije naveden omiljeni sport'), ('Fudbal', 'Fudbal'), ('Kosarka', 'Kosarka'), ('Tenis', 'Tenis'), ('Odbojka', 'Odbojka')], default='Fudbal', max_length=254),
        ),
    ]
