# Generated by Django 2.1.2 on 2018-12-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0004_dogadjaj_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='novac_za_prijavu',
            field=models.PositiveIntegerField(),
        ),
    ]
