# Generated by Django 2.1.2 on 2018-12-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0005_auto_20181217_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='datum_odrzavanja',
            field=models.DateField(),
        ),
    ]
