# Generated by Django 2.1.2 on 2018-12-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0006_auto_20181217_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='opis',
            field=models.TextField(max_length=1000),
        ),
    ]
