# Generated by Django 2.1.2 on 2018-12-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0007_auto_20181217_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='mesto',
            field=models.CharField(max_length=150),
        ),
    ]
