# Generated by Django 2.1.2 on 2018-12-16 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0008_auto_20181217_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogadjaj',
            old_name='organizator',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='dogadjaj',
            name='potrebno_igraca',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
