# Generated by Django 2.1.2 on 2018-12-17 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0010_auto_20181217_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
