# Generated by Django 2.1.2 on 2018-12-17 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogadjaji', '0011_auto_20181217_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogadjaj',
            name='user',
        ),
        migrations.AddField(
            model_name='dogadjaj',
            name='organizator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
