# Generated by Django 2.1.2 on 2018-12-17 02:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogadjaji', '0012_auto_20181217_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadjaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_kreiranja', models.DateField(default=django.utils.timezone.now)),
                ('naziv', models.CharField(max_length=150)),
                ('datum_odrzavanja', models.DateField()),
                ('opis', models.TextField(max_length=1000)),
                ('potrebno_igraca', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('novcana_nagrada', models.CharField(choices=[('Ima novcane nagrade', 'Ima novcane nagrade'), ('Nema novcane nagrade', 'Nema novcane nagrade')], default='Nema novcane nagrade', max_length=100)),
                ('novac_za_prijavu', models.PositiveIntegerField()),
                ('grad', models.CharField(choices=[('Nije naveden grad', 'Nije naveden grad'), ('Beograd', 'Beograd'), ('Cacak', 'Cacak'), ('Uzice', 'Uzice'), ('Ivanjica', 'Ivanjica'), ('Novi sad', 'Novi sad'), ('Nis', 'Nis'), ('Pozega', 'Pozega'), ('Lucani', 'Lucani')], default='Nije naveden grad', max_length=254)),
                ('mesto', models.CharField(max_length=150)),
                ('odrzano', models.BooleanField(default=False)),
                ('sport', models.CharField(choices=[('Nije naveden omiljeni sport', 'Nije naveden omiljeni sport'), ('Fudbal', 'Fudbal'), ('Kosarka', 'Kosarka'), ('Tenis', 'Tenis'), ('Odbojka', 'Odbojka')], default='Fudbal', max_length=254)),
                ('organizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dogadjaj',
            name='organizator',
        ),
        migrations.AlterField(
            model_name='prijava',
            name='prijava_za_dogadjaj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dogadjaji.Dogadjaji'),
        ),
        migrations.DeleteModel(
            name='Dogadjaj',
        ),
    ]
