# Generated by Django 2.1.2 on 2018-12-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0013_auto_20181217_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='sport',
            field=models.CharField(choices=[('Fudbal', 'Fudbal'), ('Kosarka', 'Kosarka'), ('Tenis', 'Tenis'), ('Odbojka', 'Odbojka')], default='Fudbal', max_length=254),
        ),
    ]
