# Generated by Django 2.1.2 on 2018-12-17 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0014_auto_20181217_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
