# Generated by Django 2.1.2 on 2018-12-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0015_auto_20181217_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='novcana_nagrada',
            field=models.CharField(choices=[('Nema novcane nagrade', 'Nema novcane nagrade'), ('Ima novcane nagrade', 'Ima novcane nagrade')], default='Nema novcane nagrade', max_length=100),
        ),
    ]
