# Generated by Django 2.1.2 on 2018-12-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0018_dogadjaji_asport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogadjaji',
            name='asport',
        ),
    ]
