# Generated by Django 2.1.2 on 2018-12-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0019_remove_dogadjaji_asport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnici.Clanovi'),
        ),
        migrations.AlterField(
            model_name='prijava',
            name='prijavu_poslao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnici.Clanovi'),
        ),
    ]
