# Generated by Django 2.1.2 on 2018-12-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0021_auto_20181220_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='novcana_nagrada',
            field=models.CharField(choices=[('Nema nagrada', 'Nema nagrada'), ('Ima nagrada', 'Ima nagrada')], default='Nema novcane nagrade', max_length=100),
        ),
    ]
