# Generated by Django 2.1.2 on 2018-12-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0023_dogadjaji_ima_igraca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='grad',
            field=models.CharField(choices=[('Beograd', 'Beograd'), ('Cacak', 'Cacak'), ('Uzice', 'Uzice'), ('Ivanjica', 'Ivanjica'), ('Novi sad', 'Novi sad'), ('Nis', 'Nis'), ('Pozega', 'Pozega'), ('Lucani', 'Lucani')], default='Nije naveden grad', max_length=254),
        ),
    ]
