# Generated by Django 2.1.2 on 2018-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0024_auto_20181220_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='grad',
            field=models.CharField(choices=[('Beograd', 'Beograd'), (' Valjevo', ' Valjevo'), (' Vranje', ' Vranje'), (' Zaječar', ' Zaječar'), (' Zrenjanin', ' Zrenjanin'), (' Jagodina', ' Jagodina'), (' Kragujevac', ' Kragujevac'), (' Kraljevo', ' Kraljevo'), (' Kruševac', ' Kruševac'), (' Leskovac', ' Leskovac'), (' Loznica', ' Loznica'), (' Niš', ' Niš'), (' Novi Pazar', ' Novi Pazar'), (' Novi Sad', ' Novi Sad'), (' Pančevo', ' Pančevo'), (' Požarevac', ' Požarevac'), (' Priština', ' Priština'), (' Smederevo', ' Smederevo'), (' Sombor', ' Sombor'), (' Sremska Mitrovica', ' Sremska Mitrovica'), (' Subotica', ' Subotica'), (' Užice', ' Užice'), (' Čačak', ' Čačak'), (' Šabac', ' Šabac'), (' Pirot', ' Pirot')], default='Nije naveden grad', max_length=254),
        ),
    ]
