# Generated by Django 2.1.2 on 2018-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0025_auto_20181220_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaji',
            name='sport',
            field=models.CharField(choices=[('Fudbal', 'Fudbal'), ('Kosarka', 'Kosarka'), ('Tenis', 'Tenis'), ('Odbojka', 'Odbojka'), ('Rukomet', 'Rukomet'), ('Stoni tenis', 'Stoni tenis'), ('Bilijar', 'Bilijar')], default='Fudbal', max_length=254),
        ),
    ]
