# Generated by Django 2.1.2 on 2018-12-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogadjaji', '0030_ocenjivanje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zavrsio', models.BooleanField(default=False)),
                ('igrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('koji_dogadjaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogadjaji.Dogadjaji')),
            ],
        ),
    ]
