# Generated by Django 2.1.2 on 2018-12-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0031_glasao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocenjivanje',
            old_name='organizator',
            new_name='koga_ocenio',
        ),
    ]
