# Generated by Django 2.1.2 on 2019-01-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0032_auto_20181222_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocenjivanje',
            name='komentar',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
