# Generated by Django 2.1.2 on 2019-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0033_ocenjivanje_komentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='maxo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
            ],
        ),
    ]
