# Generated by Django 2.1.2 on 2019-01-19 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0035_auto_20190115_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poziv',
            name='status',
        ),
        migrations.AddField(
            model_name='poziv',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poziv',
            name='pogledano',
            field=models.CharField(choices=[('Nije pogledano', 'Nije pogledano'), ('Jeste pogledano', 'Jeste pogledano')], default='Ceka se odgovor', max_length=100),
        ),
    ]
