# Generated by Django 2.1.2 on 2019-01-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogadjaji', '0036_auto_20190119_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poziv',
            name='pogledano',
            field=models.CharField(choices=[('Nije pogledano', 'Nije pogledano'), ('Jeste pogledano', 'Jeste pogledano')], default='Nije pogledano', max_length=100),
        ),
    ]
