# Generated by Django 2.1.2 on 2018-12-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilna_slika', models.ImageField(default='profilne_slike/default.jpg', upload_to='')),
                ('grad', models.CharField(choices=[('Nije dodato', 'Nije dodato'), ('Belgrade', 'Belgrade'), ('Cacak', 'Cacak'), ('Uzice', 'Uzice'), ('Ivanjica', 'Ivanjica'), ('Novi sad', 'Novi sad'), ('Nis', 'Nis'), ('Pozega', 'Pozega'), ('Lucani', 'Lucani'), ('Lucani', 'Lucani')], default='Nije dodato', max_length=254)),
                ('omiljeni_sport', models.CharField(default='Nije dodato', max_length=254)),
                ('pol', models.CharField(choices=[('Musko', 'Musko'), ('Zensko', 'Zensko'), ('/ ', '/')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
