# Generated by Django 2.1.2 on 2018-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0002_auto_20181212_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanovi',
            name='broj_telefona',
            field=models.CharField(default='Nije dodato', max_length=35),
        ),
    ]
