# Generated by Django 2.1.2 on 2018-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0008_auto_20181212_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='profilna_slika',
            field=models.ImageField(default='profilne_slike/default.jpg', upload_to='profilne_slike'),
        ),
    ]
