# Generated by Django 2.1.2 on 2018-12-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0009_auto_20181212_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='grad',
            field=models.CharField(choices=[('Drugi', 'Drugi'), ('Belgrade', 'Belgrade'), ('Cacak', 'Cacak'), ('Uzice', 'Uzice'), ('Ivanjica', 'Ivanjica'), ('Novi sad', 'Novi sad'), ('Nis', 'Nis'), ('Pozega', 'Pozega'), ('Lucani', 'Lucani'), ('Lucani', 'Lucani')], default='Nije dodat grad', max_length=254),
        ),
        migrations.AlterField(
            model_name='clanovi',
            name='omiljeni_sport',
            field=models.CharField(choices=[('Drugi', 'Drugi'), ('Fudbal', 'Fudbal'), ('Kosarka', 'Kosarka'), ('Tenis', 'Tenis'), ('Odbojka', 'Odbojka')], default='Nije dodat omiljeni sport', max_length=254),
        ),
    ]
