# Generated by Django 2.1.2 on 2018-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0010_auto_20181212_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanovi',
            name='prosecna_ocena',
            field=models.FloatField(default=0),
        ),
    ]
