# Generated by Django 2.1.2 on 2018-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0011_clanovi_prosecna_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='broj_telefona',
            field=models.CharField(default='Nije dodat broj telefona', max_length=35),
        ),
    ]
