# Generated by Django 2.1.2 on 2018-12-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0012_auto_20181213_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanovi',
            name='opis',
            field=models.TextField(default='Nije dodat opis', max_length=1000),
        ),
    ]
