# Generated by Django 2.1.2 on 2018-12-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0014_auto_20181215_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='grad',
            field=models.CharField(choices=[('Drugi', 'Drugi'), ('Beograd', 'Beograd'), ('Cacak', 'Cacak'), ('Uzice', 'Uzice'), ('Ivanjica', 'Ivanjica'), ('Novi sad', 'Novi sad'), ('Nis', 'Nis'), ('Pozega', 'Pozega'), ('Lucani', 'Lucani'), ('Lucani', 'Lucani')], default='Nije dodat grad', max_length=254),
        ),
    ]
