# Generated by Django 2.1.2 on 2018-12-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0015_auto_20181215_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='grad',
            field=models.CharField(choices=[('Nije naveden', 'Nije naveden'), ('Beograd', 'Beograd'), ('Cacak', 'Cacak'), ('Uzice', 'Uzice'), ('Ivanjica', 'Ivanjica'), ('Novi sad', 'Novi sad'), ('Nis', 'Nis'), ('Pozega', 'Pozega'), ('Lucani', 'Lucani')], default='Nije naveden', max_length=254),
        ),
        migrations.AlterField(
            model_name='clanovi',
            name='pol',
            field=models.CharField(choices=[('Musko', 'Musko'), ('Zensko', 'Zensko'), ('Bez navodjenja pola', 'Bez navodjenja pola')], default='Bez navodjenja pola', max_length=5),
        ),
    ]
