# Generated by Django 2.1.2 on 2018-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0017_auto_20181215_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='omiljeni_sport',
            field=models.CharField(choices=[('Nije naveden omiljeni sport', 'Nije naveden omiljeni sport'), ('Fudbal', 'Fudbal'), ('Kosarka', 'Kosarka'), ('Tenis', 'Tenis'), ('Odbojka', 'Odbojka')], default='Nije naveden omiljeni sport', max_length=254),
        ),
        migrations.AlterField(
            model_name='clanovi',
            name='pol',
            field=models.CharField(choices=[('Musko', 'Musko'), ('Zensko', 'Zensko'), ('Bez navodjenja pola', 'Bez navodjenja pola')], default='Bez navodjenja pola', max_length=20),
        ),
    ]
