# Generated by Django 2.1.2 on 2018-12-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0018_auto_20181215_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanovi',
            name='instagram',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='clanovi',
            name='twitter',
            field=models.CharField(default='', max_length=150),
        ),
    ]
