# Generated by Django 2.1.2 on 2018-12-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0019_auto_20181216_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='clanovi',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
