# Generated by Django 2.1.2 on 2018-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0021_auto_20181220_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='omiljeni_sport',
            field=models.CharField(choices=[('Nije naveden omiljeni sport', 'Nije naveden omiljeni sport'), ('Fudbal', 'Fudbal'), ('Kosarka', 'Kosarka'), ('Tenis', 'Tenis'), ('Odbojka', 'Odbojka'), ('Rukomet', 'Rukomet'), ('Stoni tenis', 'Stoni tenis'), ('Bilijar', 'Bilijar')], default='Nije naveden omiljeni sport', max_length=254),
        ),
    ]
