# Generated by Django 2.1.2 on 2018-12-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0023_auto_20181220_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='opis',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
