# Generated by Django 2.1.2 on 2018-12-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0024_auto_20181222_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanovi',
            name='opis',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
