# Generated by Django 2.1.2 on 2018-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0025_auto_20181222_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanovi',
            name='firma',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
